# Generated by Django 5.0.6 on 2024-10-23 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentorsession',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='mentorsession',
            name='mentor',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='academic_stream',
            new_name='industry',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='contact_mode',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='mentoring_frequency',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='preferred_mentee_year',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='session_duration',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mentor',
            name='education',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='mentor',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentor',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorCategory',
            fields=[
                ('mentor_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorSkill',
            fields=[
                ('mentor_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('title_review', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.IntegerField()),
                ('session_topic', models.CharField(max_length=255)),
                ('session_duration', models.IntegerField()),
                ('session_notes', models.TextField()),
                ('session_date', models.DateTimeField()),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_sessions', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.session')),
            ],
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
        migrations.DeleteModel(
            name='MentorSession',
        ),
    ]
