# Generated by Django 5.0.6 on 2024-10-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_remove_education_mentor_remove_experience_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=models.TextField(default='No bio provided'),
        ),
    ]
