# Generated by Django 5.0.4 on 2024-09-03 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('total_floors', models.IntegerField()),
                ('station_type', models.CharField(choices=[('major_hub', 'Major Hub'), ('regional', 'Regional'), ('local', 'Local')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('service', 'Service'), ('dining', 'Dining'), ('restroom', 'Restroom')], max_length=50)),
                ('floor_level', models.IntegerField()),
                ('coordinates', models.CharField(max_length=255)),
                ('operational_hours', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_features', to='stations.stationfacility')),
            ],
        ),
        migrations.CreateModel(
            name='StationLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=255)),
                ('map_data', models.FileField(upload_to='station_layouts/')),
                ('floor_level', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='stations.station')),
            ],
        ),
    ]
