name: Backup Database

on:
  schedule:
    # Runs the backup every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  backup:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        working-directory: ./backend
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client-16
        
      - name: Backup PostgreSQL database
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          BACKUP_FILE="$DB_NAME-$TIMESTAMP.sql"

          # Export database password
          export PGPASSWORD=$DB_PASSWORD

          # Run pg_dump
          pg_dump -h $DB_HOST -p $DB_PORT -U $DB_USER $DB_NAME > $BACKUP_FILE
          echo "Backup created: $BACKUP_FILE"

      - name: Upload backup as artifact
        uses: actions/upload-artifact@v3
        with:
          name: database-backup
          path: $DB_NAME-*.sql
          retention-days: 30

