name: build tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Set environment variable for the DATABASE_URL
      - name: Set environment variable
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      # - name: Run Tests
      #   working-directory: ./backend
      #   # env:
      #   #   DJANGO_SETTINGS_MODULE: backend.settings
      #   # run: pytest
      #   env:
      #     DATABASE_URL: postgresql://careerhorizon_user:SEpIIuXSAOY2gK1EiliiNAmSLT9dYtqa@dpg-ct2oj0pu0jms738u00rg-a.oregon-postgres.render.com/careerhorizon
      #     DJANGO_SETTINGS_MODULE: Navigator.settings
      #   run: pytest
          
      - name: Grant execute permissions
        working-directory: ./backend 
        run: chmod +x ./build.sh
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}

      - name: Install dependencies
        working-directory: ./backend 
        run: ./build.sh

      # Run Tests
      - name: Run Tests
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DJANGO_SETTINGS_MODULE: Navigator.settings
        run: pytest
