name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          
      # - name: Test Database Connection
      #   run: python backend/manage.py dbshell

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL
        env:
          PSQL_HOST: dpg-ct2oj0pu0jms738u00rg-a.oregon-postgres.render.com
          PSQL_PORT: 5432
          PSQL_USER: careerhorizon_user
          PSQL_PASSWORD: SEpIIuXSAOY2gK1EiliiNAmSLT9dYtqa
          PSQL_DB: careerhorizon
        run: |
          until PGPASSWORD=$PSQL_PASSWORD psql -h $PSQL_HOST -p $PSQL_PORT -U $PSQL_USER -d $PSQL_DB -c "SELECT 1"; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done


      - name: Apply migrations
        env:
          DATABASE_URL: postgresql://careerhorizon_user:SEpIIuXSAOY2gK1EiliiNAmSLT9dYtqa@dpg-ct2oj0pu0jms738u00rg-a.oregon-postgres.render.com/careerhorizon
        run: |
          python backend/manage.py makemigrations
          python backend/manage.py migrate

      - name: Run Tests
        env:
          DATABASE_URL: postgresql://careerhorizon_user:SEpIIuXSAOY2gK1EiliiNAmSLT9dYtqa@dpg-ct2oj0pu0jms738u00rg-a.oregon-postgres.render.com/careerhorizon
          DJANGO_SETTINGS_MODULE: backend.settings
        run: pytest
